function LSTMClassTarg = CommonWeightsUpdates(LSTMClassSour,LSTMClassTarg)
% used for updates weights for differnt time steps
% parameters for single cell
Paras = {   'Weights_f',...
            'Weights_i',...
            'Weights_c',...
            'Weights_o',...
            'W_Softmax',...
            'Bias_f',...
            'Bias_i',...
            'Bias_c',...
            'Bias_o',...
            'b_Softmax'};
nParas = length(Paras);
for cPara = 1 : nParas
    LSTMClassTarg.(Paras{cPara}) = LSTMClassSour.(Paras{cPara});
end
    
