function createfigure(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 10-Sep-2016 14:47:44

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot(YMatrix1,'Parent',axes1);

box(axes1,'on');
% Create line
annotation(figure1,'line',[0.228571428571429 0.508928571428571],...
    [0.953761904761905 0.954761904761905],'Color',[0 1 0],'LineWidth',2);

