function Hd = filt
%FILT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.2 and the Signal Processing Toolbox 6.20.
% Generated on: 23-Jun-2014 10:03:40

Numerator   = [0.028 0.053 0.071 0.053 0.028];  % Numerator coefficient
                                                % vector
Denominator = [1 -2.026 2.148 -1.159 0.279];    % Denominator coefficient
                                                % vector

Hd = dfilt.df2t(Numerator, Denominator);


% [EOF]
