function newax=scAddPlot(ax)
% scAddPlot superimposes a new, transparent, set of axes 
%
% Example:
% newax=scAddPlot(ax)
%     superimposes a set of axes on those specified by handle ax
%     returning the handle of the new axes
%
% -------------------------------------------------------------------------
% Author: Malcolm Lidierth 03/08
% Copyright © The Author & King's College London 2008-
% -------------------------------------------------------------------------

fhandle=ancestor(ax, 'figure');
kp=get(fhandle, 'NextPlot');
set(fhandle, 'NextPlot', 'add');
newax=axes('Position',get(ax,'Position'),...
    'Parent',get(ax,'Parent'),...
    'YAxisLocation', 'Right',...
    'Color', 'none',...
    'Hittest', 'off',...
    'Tag', 'sigTOOL: Added Plot',...
    'YLimMode', 'manual',...
    'YLim', get(ax, 'YLim'),...
    'XLimMode', 'manual',...
    'XLim', get(ax, 'XLim'),...
    'Tag', 'sigTOOL:AddedPlotAxes');
set(fhandle, 'NextPlot', kp);

return
end