function h=jvAddCoherence(h)
% jvAddCoherence addpanel function
% 
% Example:
% h=jvAddCoherence(h)
%
% -------------------------------------------------------------------------
% Author: Malcolm Lidierth 11/07
% Copyright © The Author & King's College London 2007-
% -------------------------------------------------------------------------


Height=0.09;
Top=0.75;

h=jvAddPanel(h, 'Title', 'FFT Options',...
    'dimension', 0.75);

try
    [winhandles winlist]=findallwinclasses('nonuserdefined');
    winhandles=cellfun(@str2func, winhandles, 'UniformOutput', false);
catch
    winhandles=@wvHamming;
    winlist={'Hamming'};
end

h=jvElement(h{end},'Component', 'javax.swing.JComboBox',...
    'Position',[0.1 Top 0.8 Height],...
    'DisplayList', {'1' '2' '5' '10' '20'},...
    'ReturnValues',{1, 2 , 5, 10, 20},...
    'Label', 'Window Length (s)',...
    'ToolTipText', 'Data sections length (s)');

h=jvElement(h{end},'Component', 'javax.swing.JComboBox',...
    'Position',[0.1 Top-(2*Height) 0.8 Height],...
    'DisplayList', winlist,...
    'ReturnValues', winhandles,...
    'Label', 'Window',...
    'ToolTipText', 'Available windows');
h{end}.Window.setSelectedIndex(find(strcmp(winlist,'Hamming'))-1);

h=jvElement(h{end},'Component', 'javax.swing.JComboBox',...
    'Position',[0.1 Top-(4*Height) 0.8 Height],...
    'DisplayList', {'0' '25' '50' '75'},...
    'ReturnValues', {0 25 50 75 100},...
    'Label', 'Overlap (%)',...
    'ToolTipText', 'Overlap of successive data sections');
h{end}.Overlap.setSelectedIndex(2);

h=jvElement(h{end},'Component', 'javax.swing.JComboBox',...
    'Position',[0.1 Top-(6*Height) 0.8 Height],...
    'DisplayList',  {'Coherence',...
                    'SNR'},...
    'Label', 'Mode',...
    'ToolTipText','Coherence or signal-to-noise ratio');

h=jvElement(h{end},'Component', 'javax.swing.JCheckBox',...
    'Position',[0.1 Top-(8*Height) 0.8 Height],...
    'Label', 'Detrend',...
    'ToolTipText', 'Pre-process: Remove DC & linear trend');


return
end
