function h=jvAddPhaseHistogram(h)
% jvAddPhaseHistogram addpanel function
% 
% Example:
% h=jvAddPhaseHistogram(h)
%
% -------------------------------------------------------------------------
% Author: Malcolm Lidierth 08/08
% Copyright © The Author & King's College London 2008-
% -------------------------------------------------------------------------


Height=0.09;
Top=0.75;

h=jvAddPanel(h, 'Title', 'Details',...
    'dimension', 0.6);



h=jvElement(h{end},'Component', 'javax.swing.JComboBox',...
    'Position',[0.1 Top 0.8 Height],...
    'DisplayList', {'1' '2' '5'},...
    'Label', 'Duration(cycles)',...
    'ToolTipText', 'Duration of average (cycles)');

h=jvElement(h{end},'Component', 'javax.swing.JComboBox',...
    'Position',[0.1 Top-(2*Height) 0.8 Height],...
    'DisplayList', {'1' '2' '5' '10' '20'},...
    'Label', 'Bin Width(degrees)',...
    'ToolTipText', 'Bin Width (degrees)');

h=jvElement(h{end},'Component', 'javax.swing.JComboBox',...
    'Position',[0.1 Top-(4*Height) 0.8 Height],...
    'DisplayList', {'0' '10' '20' '50'},...
    'ReturnValues', {0 10 20 50},...
    'Label', 'PreTime(%)',...
    'ToolTipText', 'Pre-trigger time');


h=jvElement(h{end},'Component', 'javax.swing.JComboBox',...
    'Position',[0.1 Top-(6*Height) 0.8 Height],...
    'DisplayList', {'All' '10' '20' '50'},...
    'ReturnValues', {0 10 20 50},...
    'Label', 'Sweeps per average',...
    'ToolTipText', 'Overlap of successive data sections');



return
end


