function h=jvAddIcasso(h)
% jvAddIcasso addpanel function
% 
% Example:
% h=jvAddIcasso(h)
%
% -------------------------------------------------------------------------
% Author: Malcolm Lidierth 11/07
% Copyright © The Author & King's College London 2007-
% -------------------------------------------------------------------------


Height=0.09;
Top=0.8;

h=jvAddPanel(h, 'Title', 'Details',...
    'dimension', 0.6);


h=jvElement(h{end},'Component', 'javax.swing.JComboBox',...
    'Position',[0.1 Top 0.8 Height],...
    'DisplayList', {'Both' 'Randinit' 'Bootstrap'},...
    'Label', 'Mode',...
    'ToolTipText', 'Number of times to run FastICA');

h=jvElement(h{end},'Component', 'javax.swing.JComboBox',...
    'Position',[0.1 Top-(1.75*Height) 0.8 Height],...
    'DisplayList', {'10' '20' '50' '100' '200'},...
    'Label', 'Iterations',...
    'ToolTipText', 'Number of times to run FastICA');

h=jvElement(h{end},'Component', 'javax.swing.JComboBox',...
    'Position',[0.1 Top-(3.5*Height) 0.8 Height],...
    'DisplayList', {'Default' '2' '3' '4' '5' '6' '7' '8' '9' '10'},...
    'Label', 'Number of components',...
    'ToolTipText', 'Number if components to extract');

h=jvElement(h{end},'Component', 'javax.swing.JTextField',...
    'Position',[0.1 Top-(5.25*Height) 0.8 Height],...
    'DisplayList', '',...
    'Label', 'FastICA optional arguments',...
    'ToolTipText', 'Enter a list of arguments');

h=jvElement(h{end},'Component', 'javax.swing.JCheckBox',...
    'Position',[0.15 Top-(6.25*Height) 0.8 Height],...
    'Label', 'Save results to sigTOOL',...
    'ToolTipText', 'Add the ICs to the sigTOOL view as new channels');

h=jvElement(h{end},'Component', 'javax.swing.JCheckBox',...
    'Position',[0.15 Top-(7*Height) 0.8 Height],...
    'Label', 'Save results to file',...
    'ToolTipText', 'Save the Icasso structure as a MAT-file');

h=jvElement(h{end},'Component', 'javax.swing.JCheckBox',...
    'Position',[0.15 Top-(7.75*Height) 0.8 Height],...
    'Label', 'Save results to MATLAB',...
    'ToolTipText', 'Save the Icasso structure to the base workspace');

return
end


